version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t zeus-monitor .
  post_build:
    commands:
      - echo Build completed on Fri Dec 19 10:43:06 PM CST 2025
